blank_issues_enabled: true
contact_links:
  - name: Issue Submission Guideline
    url: https://github.com/CyberryTeam/contributing/blob/master/SUBMISSION_GUIDELINES.md#issue
    about: Before submitting your issue, make sure you have read the Issue Submission Guideline.
